/*
We create a app directory in root of application,
which will contain all the source code.
This is a good practice to follow
because with this way we can seperate our application code
from the code that is automatically generated by our tooling.
If something happens to our project tomorrow,
we create a new react native project and simple copy our application code into project.

We copy the assets folder into app folder.
We make a new folder called screens in app folder.
We make a new file WecomeScreen.js
We import it into App.js
*/

import { StatusBar } from "expo-status-bar";
import React from "react";

import WelcomeScreen from "./app/screens/WelcomeScreen";

export default function App() {
  return <WelcomeScreen />;
}
